image:
  file: .devcontainer/Dockerfile

tasks:
  - init: make create-venv && make install-flit && make install-dev && make enable-pre-commit-hooks
    command: echo "Ready to code!"

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance 