default_language_version:
  python: python3.12

default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
        - id: absolufy-imports
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        types: [ python ]
        pass_filenames: false
      - id: secure
        name: secure
        entry: make secure
        language: system
        types: [python]
        pass_filenames: false
      - id: pytype
        name: pytype
        entry: make type-check
        language: system
        types: [python]
        pass_filenames: false
      - id: check-branch-name
        name: check-branch-name
        entry: make check-branch-name
        language: system
        pass_filenames: false
      - id: check-conventional-commit
        name: check-conventional-commit
        entry: make check-conventional-commit
        language: system
        pass_filenames: false
      - id: check-coverage
        name: check-coverage
        entry: make test-cov
        language: system
        pass_filenames: false
